### PR TITLE
fixed setup.py requirements

### PR DESCRIPTION
**Pull request by mbernico**
Just had to reinstall, noticed setup.py hard coded to some older versions of scipy, numpy, sklearn.

This PR updates setup.py such that it requires at least those versions, rather than exactly those versions.

### CODE REVIEW

**Comment by nerdcha** [comment]
:+1: This change would be great.

**Comment by mbernico** [comment]
@nerdcha I'm not sure what's going on with Daniel but in the meantime you can use my fork.  https://github.com/mbernico/boruta_py

**Comment by nerdcha** [comment]
@mbernico Good idea, thanks.

**Comment by danielhomola** [comment]
Really sorry for the long absence guys.. life got a bit hectic.. trying to catch up on my repos..

**Comment by nerdcha** [comment]
@danielhomola Thanks, sorry to pester!  😁

**Pull request merged**
